# Generated by Django 3.1.7 on 2021-03-04 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_granted', models.DateField(auto_now=True)),
                ('granted', models.BooleanField(default=False)),
                ('wisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wisher', to='WishesApp.user')),
            ],
        ),
    ]
